print("Welcome to the Band Name Generator.")
print("What's name of the city you grew up in?")
name_city = input()
print("What's your pet's name?")
name_pet = input()
print("Your band name could be", name_city, name_pet)